server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: http://47.104.85.220:88482
    sentinel:
      transport:
        #sentinel dashboard地址
        dashboard: http://localhost:8080
        #默认8719端口，假如8719被占用开始依次+1扫描，直至找到未被占用的端口
        port: 8719

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
