server:
  port: 8802

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:  #配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义名称 用于binding整合
          type: rabbit #消息组件类型
          environment: #rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 47.104.85.220
                port: 5672
                username: Young
                password: Young8614046577
      bindings: #服务整合处理
        input: #通道名称
          destination: studyExchange #要使用的Exchange名称定义
          content-type: application/json #设置消息类型
          binder: defaultRabbit #要绑定的消息服务的具体设置
          group: a

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 5 #超过5秒的时间间隔 （默认90秒）
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔 （默认为30秒）
    instance-id: send-8802.com
    prefer-ip-address: true
