server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://47.104.85.220:8848/

management:
  endpoints:
    web:
      exposure:
        include: '*'