server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://47.104.85.220:8848/

service-url:
  nacos-user-service: http://nacos-payment-provider